# Generated by Django 3.2 on 2021-08-04 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_Name', models.CharField(max_length=200)),
                ('business_Type', models.CharField(max_length=100)),
                ('mobile_No', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=500)),
                ('requirement', models.TextField()),
                ('department', models.CharField(max_length=50)),
                ('agent_id', models.IntegerField()),
            ],
        ),
    ]
