# Generated by Django 3.2 on 2021-08-04 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_agent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='agent_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.agent'),
        ),
    ]
