# Generated by Django 3.2 on 2021-08-05 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0004_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myApp.status'),
            preserve_default=False,
        ),
    ]
