# Generated by Django 3.2 on 2021-08-06 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0005_lead_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='agent_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myApp.agent'),
        ),
    ]
