# Generated by Django 3.2 on 2021-08-10 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0011_auto_20210810_1446'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='agent_Name',
        ),
    ]
